Check TestResults files

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Build
+name: .NET
 
 on:
   push:
@@ -6,36 +6,41 @@ on:
   pull_request:
     branches: [ "main" ]
 
-jobs:    
+jobs:
   build:
-    name: Build .Net
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
-
+      
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
-        dotnet-version: 8.0.x
+        dotnet-version: 7.0.x
 
     - name: Restore dependencies
       run: dotnet restore
 
     - name: Build
-      run: dotnet build --no-restore --configuration Release
+      run: dotnet build --no-restore --configuration Release   
 
     - name: Test
       run: dotnet test --no-build --verbosity normal --configuration Release
-
-  analyze:
-    name: SonarCloud
-    runs-on: ubuntu-latest
-
-    steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
+    
+    - name: Check TestResults files
+      run: |
+        if [ ! -d "TestResults" ]; then
+          echo "TestResults directory does not exist."
+          exit 1
+        fi
+        if [ ! -f TestResults/*.trx ]; then
+          echo "TRX files not found in TestResults directory."
+          exit 1
+        fi
+        if [ ! -f TestResults/**/coverage.opencover.xml ]; then
+          echo "Coverage OpenCover files not found in TestResults directory."
+          exit 1
+        fi
 
     - name: Sonar Scan
       uses: highbyte/sonarscan-dotnet@v2.3.0
@@ -44,10 +49,8 @@ jobs:
         sonarProjectName: ShortSharing
         sonarOrganization: antik88
         dotnetBuildArguments: --configuration Release
-        dotnetTestArguments: --no-build --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
-        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" /d:sonar.coverage.exclusions="${{env.EXCLUDE_FROM_COVERAGE}}" /d:sonar.exclusions="${{env.EXCLUDE_FROM_SONAR}}" 
-    env: 
-        EXCLUDE_FROM_COVERAGE: "**/Program.cs, **/Extensions/*, **/Exceptions/**, **/DI/*, **/Validators/*, **/Enums/**/*, **/MappingConfigurations/*, **/ViewModels/**, **/Controllers/*, **/Utilities/**, **/Models/**"
+        dotnetTestArguments: --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
+        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" /d:sonar.coverage.exclusions="$EXCLUDE_FROM_COVERAGE" 
+      env:
+        EXCLUDE_FROM_COVERAGE: "**/Program.cs,**/Context.cs,**/Migrations/**,**/DI/**,**/Helpers/**,**/Validators/**,**/Middlewares/**,**/Constants/**,**/Repositories/**,*.json"
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        EXCLUDE_FROM_SONAR: "**/ViewModels/**, **/Dockerfile"
-        WORKING_DIRECTORY: "ShortSharing"
